//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Careers
    {
        public int Id { get; set; }
        public string Header1 { get; set; }
        public string Content1 { get; set; }
        public string Header2 { get; set; }
        public string Content2 { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    }
}
