//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_Entities : DbContext
    {
        public DB_Entities()
            : base("name=MillsteinPlesk_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CEO> CEO { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<Investment> Investment { get; set; }
        public virtual DbSet<Locations> Locations { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Pages> Pages { get; set; }
        public virtual DbSet<Person_> Person_ { get; set; }
        public virtual DbSet<Slider> Slider { get; set; }
        public virtual DbSet<Team> Team { get; set; }
        public virtual DbSet<Advisory> Advisory { get; set; }
        public virtual DbSet<Firm> Firm { get; set; }
        public virtual DbSet<Advisory_log> Advisory_log { get; set; }
        public virtual DbSet<CEO_log> CEO_log { get; set; }
        public virtual DbSet<Contact_log> Contact_log { get; set; }
        public virtual DbSet<News_log> News_log { get; set; }
        public virtual DbSet<Pages_log> Pages_log { get; set; }
        public virtual DbSet<Person_log> Person_log { get; set; }
        public virtual DbSet<Slider_log> Slider_log { get; set; }
        public virtual DbSet<Team_log> Team_log { get; set; }
        public virtual DbSet<Firm_log> Firm_log { get; set; }
        public virtual DbSet<Careers> Careers { get; set; }
        public virtual DbSet<Investment_log> Investment_log { get; set; }
        public virtual DbSet<Careers_log> Careers_log { get; set; }
    }
}
