//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pages_log
    {
        public Pages_log()
        {
            this.Slider_log = new HashSet<Slider_log>();
        }
    
        public int Id { get; set; }
        public string Type { get; set; }
        public string Content { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public Nullable<int> Order { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual ICollection<Slider_log> Slider_log { get; set; }
    }
}
